gen_headers: arm/arm64: Add required new headers
 * required by qti_generate_kernel_headers
//kernel/msm-5.4:qti_generate_kernel_headers_arm64 generate
Headers to add:
	audio/sound/msm-cirrus-playback.h
	linux/watch_queue.h
	linux/netfilter_ipv4/ipt_TRIGGER.h
	linux/ispv2_ioparam.h
error: gen_headers blueprints file is out of date, suggested fix:
Please add or remove the above mentioned headers from kernel/msm-5.4/gen_
headers_arm64.bp

//kernel/msm-5.4:qti_generate_kernel_headers_arm generate
Headers to add:
	linux/ispv2_ioparam.h
	linux/watch_queue.h
	audio/sound/msm-cirrus-playback.h
error: gen_headers blueprints file is out of date, suggested fix:
Please add or remove the above mentioned headers from kernel/msm-5.4/gen_
headers_arm.bp

Signed-off-by: RobertGarciaa <chae0218@naver.com>